version: '3'

services:

  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-shop}
      MYSQL_ROOT_PASSWORD: ${USER_DB_PASSWORD:-password}
      MYSQL_USER: ${USER_LOGIN:-user}
      MYSQL_PASSWORD: ${USER_PASSWORD:-password}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db